import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase, getCurrentGymId } from '../lib/supabase';
import { getRandomPersonPhoto } from '../lib/memberPhoto';

// Types (inline to avoid import issues)
type MembershipPlan = 'monthly' | 'quarterly' | 'half_yearly' | 'annual';
type Gender = 'male' | 'female' | 'other';

interface MemberFormData {
  full_name: string;
  phone: string;
  email?: string;
  gender?: Gender;
  height?: string;
  weight?: string;
  joining_date: string;
  membership_plan: MembershipPlan;
  plan_amount: number;
  photo_url?: string;
}

export function useCreateMember() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (memberData: MemberFormData) => {
      const gymId = await getCurrentGymId();
      if (!gymId) throw new Error('No gym ID found');

      // Auto-generate a real person photo based on gender if not provided
      const photoUrl = memberData.photo_url || getRandomPersonPhoto(memberData.gender);

      // Create member
      const { data: member, error: memberError } = await supabase
        .from('gym_members')
        .insert({
          gym_id: gymId,
          full_name: memberData.full_name,
          email: memberData.email,
          phone: memberData.phone,
          gender: memberData.gender,
          height: memberData.height,
          weight: memberData.weight,
          joining_date: memberData.joining_date,
          membership_plan: memberData.membership_plan,
          plan_amount: memberData.plan_amount,
          photo_url: photoUrl,
          status: 'active',
        })
        .select()
        .single();

      if (memberError) throw memberError;

      // Payment schedule is auto-generated by database trigger!
      // No need to manually create it here

      return member;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['members'] });
    },
  });
}
